version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: database/Dockerfile
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: waterfall_model_database
      MYSQL_USER: moon
      MYSQL_PASSWORD: 123123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: python/Dockerfile
    container_name: python_app
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: moon
      MYSQL_PASSWORD: 123123
      MYSQL_DATABASE: waterfall_model_database
    volumes:
      - ./python:/app
    working_dir: /app 
    command: ["python3", "waterfall.py"]
    stdin_open: true   # Keep STDIN open
    tty: true          # Allocate a pseudo-TTY

volumes:
  mysql_data:
